In [2]:
import pandas as pd
import numpy as np

In [9]:
labels=['A','B','C']
mylists=[10,20,30]
arr=np.array([10,20,30])
d={1:11,2:22,3:33}

In [4]:
pd.Series(mylists)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(mylists,index=d)

1    10
2    20
3    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64