In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[[2,3]][["City","Salary"]]

     City  Salary
2  Berlin   62000
3  London   85000

In [ ]:
df.iloc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [ ]:
df.iloc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df[df["Age"]>=30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [19]:

df[(df["Age"]>=30) & (df["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000